# Generated by Django 6.0.1 on 2026-01-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('especialidad', models.CharField(help_text='Ej: Soldadura, Materiales de construcción', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='finanzas.proveedor'),
        ),
    ]
