# Generated by Django 6.0.1 on 2026-01-07 04:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_proveedor_remove_gasto_proveedor_gasto_proveedor_rel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(choices=[('BOLSA', 'Bolsa'), ('PIEZA', 'Pieza / Unidad'), ('METRO_CUBICO', 'Metro Cúbico'), ('KILO', 'Kilogramo'), ('GLOBAL', 'Global')], default='BOLSA', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo_alerta', models.DecimalField(decimal_places=2, default=5, help_text='Nivel mínimo antes de alertar stock bajo', max_digits=10)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='comprobante',
            options={'ordering': ['-subido_en'], 'verbose_name': 'Comprobante', 'verbose_name_plural': 'Comprobantes'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='es_retroactivo',
            field=models.BooleanField(default=False, help_text='Indica si el gasto se registró después de su fecha real'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='proveedor_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='finanzas.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que registró el gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto_objetivo',
            field=models.DecimalField(decimal_places=2, help_text='Presupuesto total del proyecto en Bs', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Ingreso)'), ('SALIDA', 'Salida (Uso en Obra)')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, help_text='Ej: Para cimientos del galpón', max_length=255)),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.gasto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.material')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
