# Generated by Django 6.0.1 on 2026-01-07 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_material_alter_categoria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='folder', help_text='Nombre del ícono para el frontend', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carpeta de Documentos',
                'verbose_name_plural': 'Carpetas de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='notas_contexto',
            field=models.TextField(blank=True, help_text="Contexto adicional del gasto. Ej: 'Comprobante de retiro bancario, usado para mano de obra de cimientos'"),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLAN_PAGO', 'Plan de Pago'), ('CONTRATO', 'Contrato'), ('COMPROBANTE_BANCO', 'Comprobante Bancario'), ('FACTURA', 'Factura'), ('PERMISO', 'Permiso Municipal'), ('PLANO', 'Plano/Diseño'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_documento', models.DateField(help_text='Fecha del documento (no de subida)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='finanzas.carpetadocumento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='FotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/%Y/%m/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_foto', models.DateField(blank=True, help_text='Fecha en que se tomó la foto', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='finanzas.album')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('REGISTRADOR', 'Registrador'), ('VISUALIZADOR', 'Visualizador')], default='REGISTRADOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('parentesco', models.CharField(help_text='Relación familiar. Ej: Hermana, Cuñado, Madre', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo puede acceder al sistema')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_socio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['usuario__first_name'],
            },
        ),
    ]
