# Generated by Django 6.0.1 on 2026-01-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_carpetadocumento_gasto_notas_contexto_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, help_text='Foto de la factura o comprobante del gasto', null=True, upload_to='comprobantes/%Y/%m/'),
        ),
    ]
