# Generated by Django 6.0.1 on 2026-01-24 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='gasto',
            field=models.ForeignKey(blank=True, help_text='Gasto asociado a la compra de medicamentos (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='finanzas.gasto'),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='gasto',
            field=models.ForeignKey(blank=True, help_text='Gasto asociado a la compra de vacunas (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones', to='finanzas.gasto'),
        ),
    ]
